# Generated by Django 4.2.3 on 2023-11-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='bispohosphonate_current',
            new_name='bisphosphonate_current',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='bispohosphonate_new',
            new_name='bisphosphonate_new',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='bispohosphonate_prior',
            new_name='bisphosphonate_prior',
        ),
        migrations.AlterField(
            model_name='patient',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=10),
        ),
    ]
