# Generated by Django 4.2.7 on 2023-11-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_bispohosphonate_current_patient_bisphosphonate_current_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='malfunction_of_kidney',
            new_name='falling_test_abnormal',
        ),
    ]
